// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shrimp.Data;

#nullable disable

namespace Shrimp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Shrimp.Data.Entities.DistrictEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AvailableResources")
                        .HasColumnType("int");

                    b.Property<int>("CodeForDress")
                        .HasColumnType("int");

                    b.Property<decimal>("CrimeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Curfew")
                        .HasColumnType("int");

                    b.Property<int>("NameOfDistrict")
                        .HasColumnType("int");

                    b.Property<int>("PermitsNeeded")
                        .HasColumnType("int");

                    b.Property<int>("WalkabilityRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Shrimp.Data.Entities.HouseEntity", b =>
                {
                    b.Property<int>("HouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HouseID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<decimal>("HousePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HousingAmenities")
                        .HasColumnType("int");

                    b.Property<int>("RadtiationLevels")
                        .HasColumnType("int");

                    b.Property<int>("SafetyRating")
                        .HasColumnType("int");

                    b.Property<int>("SquareFootage")
                        .HasColumnType("int");

                    b.HasKey("HouseID");

                    b.HasIndex("DistrictId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("Shrimp.Data.Entities.SchoolEntity", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolId"), 1L, 1);

                    b.Property<decimal>("Costs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfStudents")
                        .HasColumnType("int");

                    b.Property<float>("TeacherStudentRatio")
                        .HasColumnType("real");

                    b.Property<int>("TypeOfASP")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfClasses")
                        .HasColumnType("int");

                    b.HasKey("SchoolId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("Shrimp.Data.Entities.HouseEntity", b =>
                {
                    b.HasOne("Shrimp.Data.Entities.DistrictEntity", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Shrimp.Data.Entities.SchoolEntity", b =>
                {
                    b.HasOne("Shrimp.Data.Entities.DistrictEntity", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });
#pragma warning restore 612, 618
        }
    }
}
